version: '1'

services:
  wordpress:
    image: wordpress:5.9.0
    links:
        - mariadb:mysql
    environment:
        - WORDPRESS_DB_PASSWORD=password
        - WORDPRESS_DB_USER=root
    ports:
        - "80:80"
    volumes:
        - ./html:/var/www/html

  mariadb:
     image: mariadb:10.6.5
     environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=wordpress
     volumes:
        - ./database:/var/lib/mysql
